### ISSUE TITLE
Fatal Exception: org.litepal.exceptions.LitePalSupportException

### ISSUE THREAD

**Issue by Moster1h** [guolindev/LitePal#675]
```
Caused by java.lang.IllegalStateException: Couldn't read row 887, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:538)
       at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
       at org.litepal.crud.DataHandler.query(DataHandler.java:143)
       at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
       at org.litepal.FluentQuery.find(FluentQuery.java:211)
       at org.litepal.FluentQuery.find(FluentQuery.java:185)
```

**Comment by guolindev** [comment]
CursorWindow的问题请参考这条issue https://github.com/LitePalFramework/LitePal/issues/576
