### ISSUE TITLE
Cursor window allocation of 2097152 bytes failed

### ISSUE THREAD

**Issue by WangIdea** [guolindev/LitePal#710]
Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 2097152 bytes failed. 

int count = LitePal.count(CheckResultVK.class);  报错位置是这行代码

我在做公司项目的压力测试，一直会存储数据，出现了这个错误，有什么解决办法吗？

**Comment by WangIdea** [comment]
org.litepal.exceptions.LitePalSupportException: Cursor window allocation of 2097152 bytes failed. 
	at org.litepal.crud.DataHandler.mathQuery(DataHandler.java:194)
	at org.litepal.crud.QueryHandler.onCount(QueryHandler.java:180)
	at org.litepal.FluentQuery.count(FluentQuery.java:507)
	at org.litepal.Operator.count(Operator.java:381)
	at org.litepal.Operator.count(Operator.java:348)
	at org.litepal.LitePal.count(LitePal.kt:205)
	at com.android.data_record.DataRecordAPIManager.saveCheckResultVK(DataRecordAPIManager.java:147)
	at com.android.logic_center.Task.LogicCenterTaskRecord.run(LogicCenterTaskRecord.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by xiexin52k** [comment]
[https://stackoverflow.com/questions/11340257/sqlite-android-database-cursor-window-allocation-of-2048-kb-failed](url)

参考这个, 是因为游标创建太多, 就算调用了close, 在压测或者高并发的情况下, 仍然可能会出现垃圾来不及回收导致游标溢出.

**Comment by guolindev** [comment]
感谢楼上的答复，这个问题因为被提的频次比较高，建议开发者还是从使用层面来减少此类问题，框架确实很难做出优化，因为也是底层抛出来的异常。

https://github.com/guolindev/LitePal/issues/576
