### ISSUE TITLE
数据库访问和友盟的冲突了怎么办

### ISSUE THREAD

**Issue by AnJiuZhe** [guolindev/LitePal#711]
项目集成了友盟的SDK，使用LitePal访问数据库的时候，有小概率会和友盟的冲突导致闪退，下面这个是错误日志，要怎么解决呢，找友盟官方吗

SQLiteDatabase: Failed to open database '/data/user/0/com.niaodaifu.test/databases/ua.db'.
    android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY): , while compiling: PRAGMA journal_mode
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:729)
        at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:376)
        at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:316)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)

**Comment by guolindev** [comment]
Database Lock了就说明这个数据库文件目前正在被其他地方访问，你可以捕获这个异常，稍后重试就行了，可以设个定时器什么的。
