### ISSUE TITLE
Demo   publishVersion = '3.2.3'  总是报错

### ISSUE THREAD

**Issue by 332455590** [guolindev/LitePal#725]
Process: org.litepal.litepalsample, PID: 9917
    org.litepal.exceptions.DatabaseGenerateException: can not find a class named com.litepaltest.model.Classroom
        at org.litepal.LitePalBase.getSupportedFields(LitePalBase.java:196)
        at org.litepal.LitePalBase.getTableModel(LitePalBase.java:123)
        at org.litepal.tablemanager.Generator.getAllTableModels(Generator.java:74)
        at org.litepal.tablemanager.Creator.createOrUpgradeTable(Creator.java:48)
        at org.litepal.tablemanager.Generator.create(Generator.java:169)
        at org.litepal.tablemanager.Generator.create(Generator.java:207)
        at org.litepal.tablemanager.LitePalOpenHelper.onCreate(LitePalOpenHelper.java:85)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:412)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
        at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:58)
        at org.litepal.tablemanager.Connector.getDatabase(Connector.java:70)
        at org.litepal.litepalsample.activity.TableListActivity$2.run(TableListActivity.java:72)
        at java.lang.Thread.run(Thread.java:919)

**Comment by guolindev** [comment]
sorry，有几个用于单元测试的类没有注释掉，导致demo跑不过，现在已经注掉了，你可以拉下更新再试试。
