### ISSUE TITLE
为啥我使用3.2.3版本不支持使用List

### ISSUE THREAD

**Issue by nongchengqi** [guolindev/LitePal#747]
会报错
  Caused by: org.litepal.exceptions.LitePalSupportException: java.util.List has no constructor. LitePal could not handle it
        at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:616)
        at org.litepal.crud.DataHandler.query(DataHandler.java:141)
        at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159) 
        at org.litepal.FluentQuery.find(FluentQuery.java:235) 
        at org.litepal.FluentQuery.findFirst(FluentQuery.java:315) 
     
多平台都有问您。麻烦回复一下

**Comment by forJrking** [comment]
一对多保存成功了，看数据库也有关联的字段了，就是查询的时候回报上面这个错误

**Comment by xiexin52k** [comment]
这个错误看起来是在初始化表类型的时候报的错.
```java
T modelInstance = (T) createInstanceFromClass(modelClass);
```
为啥你的modleClass会传一个List呢?, 难道你是使用kotlin的时候, 使用List去接收返回值了吗?

我怀疑你用法不对.
看看我的示例代码:
表一
![TableOne](https://user-images.githubusercontent.com/19523795/128128027-08e63a66-5115-4da5-891c-01d9bbfa5049.png)

表二
![TableTwo](https://user-images.githubusercontent.com/19523795/128128044-424ed6ba-f3e2-4c0b-b117-6e8da6eea525.png)

写入
![QQ截图20210804134023](https://user-images.githubusercontent.com/19523795/128128158-0a67bae9-76fe-4e06-bc14-ce0997ecf151.png)

查询
![QQ截图20210804134105](https://user-images.githubusercontent.com/19523795/128128189-12758620-1dd1-4c33-a6a0-2129f1fcc18f.png)
