### ISSUE TITLE
混淆之后报错 can not parse the litepal.xml

### ISSUE THREAD

**Issue by WZero** [guolindev/LitePal#761]
配置的混淆
`-keep class org.litepal.** {*;}
-keep class * extends org.litepal.crud.LitePalSupport {*;}`

报错日志

`Caused by: org.litepal.exceptions.ParseConfigurationFileException: can not parse the litepal.xml, check if it's in correct format
        at org.litepal.parser.LitePalParser.usePullParse(LitePalParser.java:180)
        at org.litepal.parser.LitePalParser.parseLitePalConfiguration(LitePalParser.java:102)
        at org.litepal.parser.LitePalAttr.loadLitePalXMLConfiguration(LitePalAttr.java:99)
        at org.litepal.parser.LitePalAttr.getInstance(LitePalAttr.java:90)
        at org.litepal.tablemanager.Connector.buildConnection(Connector.java:85)
        at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:57)
        at org.litepal.tablemanager.Connector.getDatabase(Connector.java:70)
        at org.litepal.Operator.findAll(Operator.java:1063)
        at org.litepal.Operator.findAll(Operator.java:1033)
        at org.litepal.LitePal.findAll(LitePal.kt:731)`

不加混淆可以正常使用。麻烦郭婶帮忙看下

**Comment by guolindev** [comment]
你在build.gradle里面加上这段配置试试呢：

```gradle
android {
    aaptOptions {
        noCompress '.xml'
    }
}
```
